/**
 * AUTOGENERATED GAME CATALOG FACT REPOSITORY
 * DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-game-catalog.ts
 *
 * PROVENANCE:
 *   source repository: https://github.com/manhthien2005/knight_build
 *   source commit:     702e1353f638de76602b2e4ee4ea5b4319e179c5
 *   source paths:      vendor/game/Zeus_Knight.jar, vendor/game/zeus-jar.json
 *   source jar sha256: 47d822f0a4d30f0d05d34aee0957c194c09b7e3a81c4be343693a12121a0b29a
 *   CTL_VERSION:       13
 *
 * TOTALS:
 *   referenced maps:  101
 *   travel eligible:  76
 *   servers:          8
 */

export interface GeneratedGameMap {
  readonly id: number;
  readonly rawNameVi: string | null;
  readonly rawNameEn?: string | null;
  readonly adjacentTo: readonly number[];
  readonly travelEligible: boolean;
}

export interface GeneratedGameServer {
  readonly index: number;
  readonly name: string;
  readonly host: string;
}

export interface GeneratedCatalogMetadata {
  readonly sourceRepository: string;
  readonly sourceCommit: string;
  readonly sourceJarSha256: string;
  readonly ctlVersion: number;
  readonly sourcePaths: readonly string[];
  readonly totalMapCount: number;
  readonly travelEligibleMapCount: number;
  readonly totalServerCount: number;
}

export const GENERATED_CATALOG_METADATA: GeneratedCatalogMetadata = {
  sourceRepository: "https://github.com/manhthien2005/knight_build",
  sourceCommit: "702e1353f638de76602b2e4ee4ea5b4319e179c5",
  sourceJarSha256: "47d822f0a4d30f0d05d34aee0957c194c09b7e3a81c4be343693a12121a0b29a",
  ctlVersion: 13,
  sourcePaths: ["vendor/game/Zeus_Knight.jar","vendor/game/zeus-jar.json"],
  totalMapCount: 101,
  travelEligibleMapCount: 76,
  totalServerCount: 8,
} as const;

export const GENERATED_GAME_SERVERS: readonly GeneratedGameServer[] = [
  {
    "index": 0,
    "name": "Chiến Thần",
    "host": "hs1.teamobi.com"
  },
  {
    "index": 1,
    "name": "Rồng Lửa",
    "host": "hs2.teamobi.com"
  },
  {
    "index": 2,
    "name": "Global Server",
    "host": "hsglobal.teamobi.com"
  },
  {
    "index": 3,
    "name": "Phượng Hoàng",
    "host": "hs3.teamobi.com"
  },
  {
    "index": 4,
    "name": "Nhân Mã",
    "host": "hs5.teamobi.com"
  },
  {
    "index": 5,
    "name": "Kì Lân",
    "host": "hs6.teamobi.com"
  },
  {
    "index": 6,
    "name": "Thiên Hà (New)",
    "host": "hs7.teamobi.com"
  },
  {
    "index": 7,
    "name": "Thách Đấu",
    "host": "hs4.teamobi.com"
  }
] as const;

export const GENERATED_GAME_MAPS: readonly GeneratedGameMap[] = [
  {
    "id": 0,
    "rawNameVi": "Ngôi Làng Nhỏ",
    "rawNameEn": "Small Village",
    "adjacentTo": [
      1
    ],
    "travelEligible": true
  },
  {
    "id": 1,
    "rawNameVi": "Làng Sói Trắng",
    "rawNameEn": "Wolf Village",
    "adjacentTo": [
      0,
      2,
      3,
      7,
      50
    ],
    "travelEligible": true
  },
  {
    "id": 2,
    "rawNameVi": "Khu mỏ",
    "rawNameEn": "Mines",
    "adjacentTo": [
      1
    ],
    "travelEligible": true
  },
  {
    "id": 3,
    "rawNameVi": "Bìa Rừng",
    "rawNameEn": "Edge of the Forest",
    "adjacentTo": [
      1,
      4
    ],
    "travelEligible": true
  },
  {
    "id": 4,
    "rawNameVi": "Hang Lửa",
    "rawNameEn": "Fire Cave",
    "adjacentTo": [
      3,
      5
    ],
    "travelEligible": true
  },
  {
    "id": 5,
    "rawNameVi": "Rừng Ảo Giác",
    "rawNameEn": "Illusion Forest",
    "adjacentTo": [
      4,
      6
    ],
    "travelEligible": true
  },
  {
    "id": 6,
    "rawNameVi": "Khe Vực",
    "rawNameEn": "Canyon",
    "adjacentTo": [
      5
    ],
    "travelEligible": true
  },
  {
    "id": 7,
    "rawNameVi": "Cánh Đồng Sói",
    "rawNameEn": "Wolf Prairie",
    "adjacentTo": [
      1,
      8,
      11,
      15,
      18
    ],
    "travelEligible": true
  },
  {
    "id": 8,
    "rawNameVi": "Thung Lũng Kỳ Bí",
    "rawNameEn": "Mysterious Valley",
    "adjacentTo": [
      7,
      9
    ],
    "travelEligible": true
  },
  {
    "id": 9,
    "rawNameVi": "Hồ Ký Ức",
    "rawNameEn": "Memory Lake",
    "adjacentTo": [
      8,
      10
    ],
    "travelEligible": true
  },
  {
    "id": 10,
    "rawNameVi": "Bãi Đất Trống",
    "rawNameEn": "Empty Zone",
    "adjacentTo": [
      9
    ],
    "travelEligible": true
  },
  {
    "id": 11,
    "rawNameVi": "Bờ Biển",
    "rawNameEn": "Coast",
    "adjacentTo": [
      7,
      12
    ],
    "travelEligible": true
  },
  {
    "id": 12,
    "rawNameVi": "Vực Đá",
    "rawNameEn": "Rock Cliff",
    "adjacentTo": [
      11,
      13
    ],
    "travelEligible": true
  },
  {
    "id": 13,
    "rawNameVi": "Rặng Đá Ngầm",
    "rawNameEn": "Barrier Reef",
    "adjacentTo": [
      12,
      14
    ],
    "travelEligible": true
  },
  {
    "id": 14,
    "rawNameVi": "Nghĩa Địa Tàu Đắm",
    "rawNameEn": "Shipwreck",
    "adjacentTo": [
      13
    ],
    "travelEligible": true
  },
  {
    "id": 15,
    "rawNameVi": "Đầm Lầy",
    "rawNameEn": "Swamp",
    "adjacentTo": [
      7,
      16
    ],
    "travelEligible": true
  },
  {
    "id": 16,
    "rawNameVi": "Đền Cổ",
    "rawNameEn": "Ancient Temple",
    "adjacentTo": [
      15,
      17
    ],
    "travelEligible": true
  },
  {
    "id": 17,
    "rawNameVi": "Hang Dơi",
    "rawNameEn": "Bat Cave",
    "adjacentTo": [
      16
    ],
    "travelEligible": true
  },
  {
    "id": 18,
    "rawNameVi": "Hang Sói Quỷ",
    "rawNameEn": "Devil Wolf Cave",
    "adjacentTo": [
      7,
      25
    ],
    "travelEligible": true
  },
  {
    "id": 19,
    "rawNameVi": "Cửa Biển",
    "rawNameEn": "Sea Coast",
    "adjacentTo": [
      24,
      47,
      67
    ],
    "travelEligible": true
  },
  {
    "id": 20,
    "rawNameVi": "Sa Mạc",
    "rawNameEn": "Desert",
    "adjacentTo": [
      23,
      34
    ],
    "travelEligible": true
  },
  {
    "id": 21,
    "rawNameVi": "Đồi Cát",
    "rawNameEn": "Sand Dune",
    "adjacentTo": [
      24,
      37
    ],
    "travelEligible": true
  },
  {
    "id": 22,
    "rawNameVi": "Vực Lún",
    "rawNameEn": "Subsidence Zone",
    "adjacentTo": [
      24,
      42
    ],
    "travelEligible": true
  },
  {
    "id": 23,
    "rawNameVi": "Hố Tử Thần",
    "rawNameEn": "Death Pit",
    "adjacentTo": [
      20,
      24
    ],
    "travelEligible": true
  },
  {
    "id": 24,
    "rawNameVi": "Nghĩa địa cát",
    "rawNameEn": "Sandy Graveyard",
    "adjacentTo": [
      19,
      21,
      22,
      23
    ],
    "travelEligible": true
  },
  {
    "id": 25,
    "rawNameVi": "Rừng Chết",
    "rawNameEn": "Dead Forest",
    "adjacentTo": [
      18,
      26,
      33
    ],
    "travelEligible": true
  },
  {
    "id": 26,
    "rawNameVi": "Suối Ma",
    "rawNameEn": "Hot Springs",
    "adjacentTo": [
      25,
      27
    ],
    "travelEligible": true
  },
  {
    "id": 27,
    "rawNameVi": "Thung Lũng Đá",
    "rawNameEn": "Stone Valley",
    "adjacentTo": [
      26,
      28
    ],
    "travelEligible": true
  },
  {
    "id": 28,
    "rawNameVi": "Boss Guardian",
    "rawNameEn": "Guardian Boss",
    "adjacentTo": [
      27
    ],
    "travelEligible": true
  },
  {
    "id": 29,
    "rawNameVi": "Hầm Mộ Tầng 1",
    "rawNameEn": "Catacomb Level 1",
    "adjacentTo": [
      30,
      35
    ],
    "travelEligible": true
  },
  {
    "id": 30,
    "rawNameVi": "Hầm Mộ Tầng 2",
    "rawNameEn": "Catacomb Level 2",
    "adjacentTo": [
      29,
      31
    ],
    "travelEligible": true
  },
  {
    "id": 31,
    "rawNameVi": "Hầm Mộ Tầng 3",
    "rawNameEn": "Catacomb Level 3",
    "adjacentTo": [
      30,
      32
    ],
    "travelEligible": true
  },
  {
    "id": 32,
    "rawNameVi": "Hầm mộ quái vật",
    "rawNameEn": "Mummy Boss",
    "adjacentTo": [
      31
    ],
    "travelEligible": true
  },
  {
    "id": 33,
    "rawNameVi": "Thành Phố Kho Báu",
    "rawNameEn": "City of Gold",
    "adjacentTo": [
      25,
      34,
      35,
      36,
      46
    ],
    "travelEligible": true
  },
  {
    "id": 34,
    "rawNameVi": "Khu phía Tây",
    "rawNameEn": "West Side",
    "adjacentTo": [
      20,
      33
    ],
    "travelEligible": true
  },
  {
    "id": 35,
    "rawNameVi": "Khu phía Đông",
    "rawNameEn": "East Side",
    "adjacentTo": [
      29,
      33
    ],
    "travelEligible": true
  },
  {
    "id": 36,
    "rawNameVi": "Đấu Trường",
    "rawNameEn": "Arena",
    "adjacentTo": [
      33
    ],
    "travelEligible": true
  },
  {
    "id": 37,
    "rawNameVi": "Rừng cao nguyên",
    "rawNameEn": "Terrace",
    "adjacentTo": [
      21,
      38
    ],
    "travelEligible": true
  },
  {
    "id": 38,
    "rawNameVi": "Con đường hiểm trở",
    "rawNameEn": "Mountain Pass",
    "adjacentTo": [
      37,
      39
    ],
    "travelEligible": true
  },
  {
    "id": 39,
    "rawNameVi": "Vách đá cheo leo",
    "rawNameEn": "Cliff",
    "adjacentTo": [
      38,
      40
    ],
    "travelEligible": true
  },
  {
    "id": 40,
    "rawNameVi": "Núi Cầu Vòng",
    "rawNameEn": "Rainbow Mountain",
    "adjacentTo": [
      39,
      41
    ],
    "travelEligible": true
  },
  {
    "id": 41,
    "rawNameVi": "Lối lên Thượng giới",
    "rawNameEn": "Entrance to Upper World",
    "adjacentTo": [
      40,
      51
    ],
    "travelEligible": true
  },
  {
    "id": 42,
    "rawNameVi": "Đèo hoang sơ",
    "rawNameEn": "Narrow Pass",
    "adjacentTo": [
      22,
      43
    ],
    "travelEligible": true
  },
  {
    "id": 43,
    "rawNameVi": "Đường xuống lòng đất",
    "rawNameEn": "Underground Entrance",
    "adjacentTo": [
      42,
      44
    ],
    "travelEligible": true
  },
  {
    "id": 44,
    "rawNameVi": "Cây cầu ma ám",
    "rawNameEn": "Cliff",
    "adjacentTo": [
      43,
      45
    ],
    "travelEligible": true
  },
  {
    "id": 45,
    "rawNameVi": "Cổng vào Hạ giới",
    "rawNameEn": "Entrance to Lower World",
    "adjacentTo": [
      44,
      52
    ],
    "travelEligible": true
  },
  {
    "id": 46,
    "rawNameVi": "Đấu Trường",
    "rawNameEn": "Arena",
    "adjacentTo": [
      33
    ],
    "travelEligible": true
  },
  {
    "id": 47,
    "rawNameVi": "Đồi xác chết",
    "rawNameEn": "Corpse Hill",
    "adjacentTo": [
      19
    ],
    "travelEligible": true
  },
  {
    "id": 48,
    "rawNameVi": "Ngã tư tử thần",
    "rawNameEn": "Crossroads of death",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 49,
    "rawNameVi": "Phó bản mới",
    "rawNameEn": "Phó bản mới",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 50,
    "rawNameVi": "Khu vườn",
    "rawNameEn": "Garden",
    "adjacentTo": [
      1
    ],
    "travelEligible": true
  },
  {
    "id": 51,
    "rawNameVi": "Cổng thiên đàng",
    "rawNameEn": "Heaven Gate",
    "adjacentTo": [
      41
    ],
    "travelEligible": true
  },
  {
    "id": 52,
    "rawNameVi": "Cổng địa ngục",
    "rawNameEn": "Hell Gate",
    "adjacentTo": [
      45,
      62
    ],
    "travelEligible": true
  },
  {
    "id": 53,
    "rawNameVi": "Chuẩn bị",
    "rawNameEn": "Equip",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 54,
    "rawNameVi": "Làng ánh sáng",
    "rawNameEn": "Light Village",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 55,
    "rawNameVi": "Chuẩn bị",
    "rawNameEn": "Equip",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 56,
    "rawNameVi": "Làng gió",
    "rawNameEn": "Wind Village",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 57,
    "rawNameVi": "Chuẩn bị",
    "rawNameEn": "Prepare",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 58,
    "rawNameVi": "Làng sét",
    "rawNameEn": "Lightning Village",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 59,
    "rawNameVi": "Chuẩn bị",
    "rawNameEn": "Prepare",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 60,
    "rawNameVi": "Làng lửa",
    "rawNameEn": "Fire Village",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 61,
    "rawNameVi": "Chiến trường",
    "rawNameEn": "Battlefield",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 62,
    "rawNameVi": "Địa ngục tầng 1",
    "rawNameEn": "Hell floors 1",
    "adjacentTo": [
      52
    ],
    "travelEligible": true
  },
  {
    "id": 63,
    "rawNameVi": "Rừng medusa",
    "rawNameEn": "Forest medusa",
    "adjacentTo": [
      64,
      65,
      70,
      72
    ],
    "travelEligible": true
  },
  {
    "id": 64,
    "rawNameVi": "Rừng Chimera",
    "rawNameEn": "Forest Chimera",
    "adjacentTo": [
      63,
      66,
      70,
      71
    ],
    "travelEligible": true
  },
  {
    "id": 65,
    "rawNameVi": "Rừng quái vật",
    "rawNameEn": "Forest monsters",
    "adjacentTo": [
      63,
      68
    ],
    "travelEligible": true
  },
  {
    "id": 66,
    "rawNameVi": "Thác reo",
    "rawNameEn": "Waterfall",
    "adjacentTo": [
      64,
      69
    ],
    "travelEligible": true
  },
  {
    "id": 67,
    "rawNameVi": "Thành phố cảng",
    "rawNameEn": "Harbor Town",
    "adjacentTo": [
      19,
      68,
      69,
      70
    ],
    "travelEligible": true
  },
  {
    "id": 68,
    "rawNameVi": "Khu bờ nam",
    "rawNameEn": "Area south shore",
    "adjacentTo": [
      65,
      67
    ],
    "travelEligible": true
  },
  {
    "id": 69,
    "rawNameVi": "Khu bờ bắc",
    "rawNameEn": "Area north shore",
    "adjacentTo": [
      66,
      67
    ],
    "travelEligible": true
  },
  {
    "id": 70,
    "rawNameVi": "Khu bờ tây",
    "rawNameEn": "Area west coast",
    "adjacentTo": [
      63,
      64,
      67
    ],
    "travelEligible": true
  },
  {
    "id": 71,
    "rawNameVi": "Rừng chuột",
    "rawNameEn": "forest mouse",
    "adjacentTo": [
      64,
      73
    ],
    "travelEligible": true
  },
  {
    "id": 72,
    "rawNameVi": "Rừng hoa đỏ",
    "rawNameEn": "red flower Forest",
    "adjacentTo": [
      63,
      73
    ],
    "travelEligible": true
  },
  {
    "id": 73,
    "rawNameVi": "Vịnh Caribe",
    "rawNameEn": "Gulf Caribe ",
    "adjacentTo": [
      71,
      72,
      74
    ],
    "travelEligible": true
  },
  {
    "id": 74,
    "rawNameVi": "Mê cung",
    "rawNameEn": "Maze",
    "adjacentTo": [
      73,
      75
    ],
    "travelEligible": true
  },
  {
    "id": 75,
    "rawNameVi": "Mê cung tầng 1",
    "rawNameEn": "Maze Floor 1",
    "adjacentTo": [
      74,
      76
    ],
    "travelEligible": true
  },
  {
    "id": 76,
    "rawNameVi": "Mê cung tầng 2",
    "rawNameEn": "Maze Floor 2",
    "adjacentTo": [
      75,
      77
    ],
    "travelEligible": true
  },
  {
    "id": 77,
    "rawNameVi": "Mê cung tầng 3",
    "rawNameEn": "Maze Floor 3",
    "adjacentTo": [
      76,
      78
    ],
    "travelEligible": true
  },
  {
    "id": 78,
    "rawNameVi": "Mê cung tầng 4",
    "rawNameEn": "Maze Floor 4",
    "adjacentTo": [
      77,
      79
    ],
    "travelEligible": true
  },
  {
    "id": 79,
    "rawNameVi": "Mê cung tầng cuối",
    "rawNameEn": "Maze Final Floor",
    "adjacentTo": [
      78,
      92
    ],
    "travelEligible": true
  },
  {
    "id": 80,
    "rawNameVi": "Thi đấu",
    "rawNameEn": "PK",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 81,
    "rawNameVi": "",
    "rawNameEn": "",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 82,
    "rawNameVi": "Khu mua bán",
    "rawNameEn": "Marketplace",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 83,
    "rawNameVi": "Cửa đông",
    "rawNameEn": "East Door",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 84,
    "rawNameVi": "Cửa tây",
    "rawNameEn": "West Door",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 85,
    "rawNameVi": "Cửa nam",
    "rawNameEn": "South Door",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 86,
    "rawNameVi": "Cửa bắc",
    "rawNameEn": "North Door",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 87,
    "rawNameVi": "Đấu trường",
    "rawNameEn": "Arena",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 88,
    "rawNameVi": "Map 88",
    "rawNameEn": "Map 88",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 89,
    "rawNameVi": "Map 89",
    "rawNameEn": "Map 89",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 90,
    "rawNameVi": "Map 90",
    "rawNameEn": "Map 90",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 91,
    "rawNameVi": "Map 91",
    "rawNameEn": "Map 91",
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 92,
    "rawNameVi": "Cổng trắng",
    "rawNameEn": null,
    "adjacentTo": [
      79,
      93
    ],
    "travelEligible": true
  },
  {
    "id": 93,
    "rawNameVi": "Thị trấn mùa đông",
    "rawNameEn": null,
    "adjacentTo": [
      92,
      94
    ],
    "travelEligible": true
  },
  {
    "id": 94,
    "rawNameVi": "Thung lũng băng giá",
    "rawNameEn": null,
    "adjacentTo": [
      93,
      95
    ],
    "travelEligible": true
  },
  {
    "id": 95,
    "rawNameVi": "Chân núi tuyết",
    "rawNameEn": null,
    "adjacentTo": [
      94,
      96
    ],
    "travelEligible": true
  },
  {
    "id": 96,
    "rawNameVi": "Đèo băng giá",
    "rawNameEn": null,
    "adjacentTo": [
      95,
      97
    ],
    "travelEligible": true
  },
  {
    "id": 97,
    "rawNameVi": "Vực thẳm sương mù",
    "rawNameEn": null,
    "adjacentTo": [
      96,
      98
    ],
    "travelEligible": true
  },
  {
    "id": 98,
    "rawNameVi": "Trạm núi tuyết",
    "rawNameEn": null,
    "adjacentTo": [
      97
    ],
    "travelEligible": true
  },
  {
    "id": 127,
    "rawNameVi": null,
    "rawNameEn": null,
    "adjacentTo": [],
    "travelEligible": false
  },
  {
    "id": 135,
    "rawNameVi": "Làng Phủ Sương",
    "rawNameEn": null,
    "adjacentTo": [
      1,
      127
    ],
    "travelEligible": false
  }
] as const;

export const GENERATED_GAME_MAP_BY_ID = new Map<number, GeneratedGameMap>(
  GENERATED_GAME_MAPS.map((map) => [map.id, map]),
);

export const GENERATED_GAME_SERVER_BY_INDEX = new Map<number, GeneratedGameServer>(
  GENERATED_GAME_SERVERS.map((server) => [server.index, server]),
);
