/**
 * AUTOGENERATED STABLE SERVER CATALOG FACT REPOSITORY
 * DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-server-catalog.ts
 *
 * PROVENANCE:
 *   source repository: https://github.com/manhthien2005/knight_build.git
 *   source commit:     3bbcc882f4b93756e13815b0eb8a4ea04dcc0be4
 *   source path:       tool/crates/zeus-core/src/rms.rs
 *   source jar sha256: b2bc6ceb5922ff05c7ae252741c7829e0d5cb81e74003d5035f80870744c6658
 *   CTL_VERSION:       15
 *   servers:           9
 */

export interface GeneratedServerEntry {
  readonly logicalId: number;
  readonly name: string;
  readonly host: string;
  readonly port: number;
  readonly lang: number;
}

export interface GeneratedServerCatalogMetadata {
  readonly sourceRepository: string;
  readonly sourceCommit: string;
  readonly sourceJarSha256: string;
  readonly ctlVersion: number;
  readonly sourcePath: string;
  readonly serverCount: number;
}

export const GENERATED_SERVER_CATALOG_METADATA: GeneratedServerCatalogMetadata = {
  "sourceRepository": "https://github.com/manhthien2005/knight_build.git",
  "sourceCommit": "3bbcc882f4b93756e13815b0eb8a4ea04dcc0be4",
  "sourceJarSha256": "b2bc6ceb5922ff05c7ae252741c7829e0d5cb81e74003d5035f80870744c6658",
  "ctlVersion": 15,
  "sourcePath": "tool/crates/zeus-core/src/rms.rs",
  "serverCount": 9
} as const;

export const STABLE_SERVER_CATALOG: readonly GeneratedServerEntry[] = [
  {
    "logicalId": 0,
    "name": "Chiến Thần",
    "host": "hs1.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 1,
    "name": "Rồng Lửa",
    "host": "hs2.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 2,
    "name": "Global Server",
    "host": "hsglobal.teamobi.com",
    "port": 19129,
    "lang": 1
  },
  {
    "logicalId": 3,
    "name": "Phượng Hoàng",
    "host": "hs3.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 4,
    "name": "Nhân Mã",
    "host": "hs5.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 5,
    "name": "Kì Lân",
    "host": "hs6.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 6,
    "name": "Thiên Hà (New)",
    "host": "hs7.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 7,
    "name": "Thách Đấu",
    "host": "hs4.teamobi.com",
    "port": 19129,
    "lang": 0
  },
  {
    "logicalId": 8,
    "name": "Bạch Hổ New",
    "host": "hs8.teamobi.com",
    "port": 19129,
    "lang": 0
  }
] as const;

export const STABLE_SERVER_BY_LOGICAL_ID: ReadonlyMap<number, GeneratedServerEntry> = new Map(
  STABLE_SERVER_CATALOG.map((server) => [server.logicalId, server]),
);
